using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Game.Packets.Helpers
{
    // Generated by Copilot. Enjoy with care!
    public struct ConnectToKey
    {
        private ulong raw; // Represents the raw 64-bit value

        // Properties to access the fields
        public uint AccountId
        {
            get => (uint)(raw & 0xFFFFFFFF); // Extract the lower 32 bits
            set => raw = raw & ~0xFFFFFFFFUL | value & 0xFFFFFFFFUL;
        }

        public byte ConnectionType
        {
            get => (byte)(raw >> 32 & 0x1); // Extract the 33rd bit (bit 32) as a byte
            set => raw = raw & ~(0x1UL << 32) | (ulong)(value & 0x1) << 32;
        }

        public uint Key
        {
            get => (uint)(raw >> 33 & 0x7FFFFFFF); // Extract bits 33-63 (31 bits)
            set => raw = raw & ~(0x7FFFFFFFUL << 33) | (value & 0x7FFFFFFFUL) << 33;
        }

        // Property to access the raw 64-bit value
        public ulong Raw
        {
            get => raw;
            set => raw = value;
        }
    }
}
