using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Packets.GamePackets.Helpers
{
    // Generated by Copilot. Enjoy with care!
    public struct ConnectToKey
    {
        public ConnectToKey() { }

        public ConnectToKey(ulong key)
        {
            Raw = key;
        }

        private ulong raw;

        public ulong Raw
        {
            get => raw;
            set => raw = value;
        }

        public uint AccountId
        {
            get => (uint)(raw & 0xFFFFFFFF); // Extract the lower 32 bits
            set => raw = (raw & 0xFFFFFFFF00000000) | value; // Set the lower 32 bits
        }

        public byte ConnectionType
        {
            get => (byte)((raw >> 32) & 0x1); // Extract the 33rd bit
            set => raw = (raw & 0xFFFFFFFFFFFEFFFF) | ((ulong)value << 32); // Set the 33rd bit
        }

        public uint Key
        {
            get => (uint)((raw >> 33) & 0x7FFFFFFF); // Extract the upper 31 bits
            set => raw = (raw & 0x1FFFFFFFF) | ((ulong)value << 33); // Set the upper 31 bits
        }
    }
}
